"""initial

Revision ID: 5429e226041c
Revises: 85b744408830
Create Date: 2026-04-09 20:35:12.930113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5429e226041c'
down_revision: Union[str, Sequence[str], None] = '85b744408830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gestational_age_weeks', sa.SmallInteger(), nullable=False),
    sa.Column('postnatal_age_days', sa.SmallInteger(), nullable=False),
    sa.Column('admission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('ai_results',
    sa.Column('result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('sepsis_score', sa.Float(), nullable=False),
    sa.Column('apnea_score', sa.Float(), nullable=False),
    sa.Column('cardiac_score', sa.Float(), nullable=False),
    sa.Column('sepsis_label', sa.SmallInteger(), nullable=False),
    sa.Column('apnea_label', sa.SmallInteger(), nullable=False),
    sa.Column('cardiac_label', sa.SmallInteger(), nullable=False),
    sa.Column('model_used', sa.String(length=32), nullable=False),
    sa.Column('shap_values_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('ix_ai_results_patient_timestamp', 'ai_results', ['patient_id', 'timestamp'], unique=False)
    op.create_table('signal_streams',
    sa.Column('stream_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_index('ix_signal_streams_patient_id', 'signal_streams', ['patient_id'], unique=False)
    op.create_table('threshold_rules',
    sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('signal_type', sa.String(length=16), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('ix_threshold_patient_signal', 'threshold_rules', ['patient_id', 'signal_type'], unique=False)
    op.create_table('vital_measurements',
    sa.Column('measurement_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stream_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('signal_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('gestational_age_weeks', sa.SmallInteger(), nullable=True),
    sa.Column('postnatal_age_days', sa.SmallInteger(), nullable=True),
    sa.Column('pma_weeks', sa.Float(), nullable=True),
    sa.Column('label_sepsis', sa.SmallInteger(), nullable=True),
    sa.Column('label_apnea', sa.SmallInteger(), nullable=True),
    sa.Column('label_cardiac', sa.SmallInteger(), nullable=True),
    sa.Column('label_healthy', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id'], ['signal_streams.stream_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.create_index('ix_vital_patient_timestamp', 'vital_measurements', ['patient_id', 'timestamp'], unique=False)
    op.create_index('ix_vital_signal_type', 'vital_measurements', ['signal_type'], unique=False)
    op.create_index('ix_vital_timestamp', 'vital_measurements', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('measurement_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['measurement_id'], ['vital_measurements.measurement_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['threshold_rules.rule_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_patient_status', 'alerts', ['patient_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_patient_status', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_vital_timestamp', table_name='vital_measurements')
    op.drop_index('ix_vital_signal_type', table_name='vital_measurements')
    op.drop_index('ix_vital_patient_timestamp', table_name='vital_measurements')
    op.drop_table('vital_measurements')
    op.drop_index('ix_threshold_patient_signal', table_name='threshold_rules')
    op.drop_table('threshold_rules')
    op.drop_index('ix_signal_streams_patient_id', table_name='signal_streams')
    op.drop_table('signal_streams')
    op.drop_index('ix_ai_results_patient_timestamp', table_name='ai_results')
    op.drop_table('ai_results')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
